id: A4E486F71
title: Toh_522-The_Dharani_of_the_Tathagata_Jnanolka-v1
type: translation
pechas:
- IF3C331C5
- IDD876D7D
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-088-016
  eft-text-version: 1.1.11 2021
  title: Toh_522-The_Dharani_of_the_Tathagata_Jnanolka-v1
alignment_to_base:
  IF3C331C5/24F4: 1AC1
  IDD876D7D/AA29: 1AC1
